Description of clipPolygonHP
Home > imael > geom2d > clipPolygonHP.m
clipPolygonHP
PURPOSE
CLIPPOLYGONHP clip a polygon with a Half-plane defined by a directed line
SYNOPSIS
function poly2 = clipPolygonHP(poly, line)
DESCRIPTION
CLIPPOLYGONHP clip a polygon with a Half-plane defined by a directed line
   POLY2 = clipPolygonHP(POLY, LINE)
   POLY is a [Nx2] array of points, and LINE is given as [x0 y0 dx dy].
   The result POLY2 is also an array of points, sometimes smaller than
   poly, and that can be [0x2] (empty polygon).
   See also:
   polygons2d, clipPolygon
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 31/07/2005.
CROSS-REFERENCE INFORMATION
This function calls:
intersectLineEdge INTERSECTLINEEDGE return intersection between a line and an edge
isLeftOriented ISLEFTORIENTED check if a point is on the left side of a line
This function is called by:
polygonExpand POLYGONEXPAND 'expand' a polygon with a given distance