Description of drawRay
Home > imael > geom2d > drawRay.m
drawRay
PURPOSE
DRAWRAY draw a ray on the current axis
SYNOPSIS
function varargout = drawRay(ray, varargin)
DESCRIPTION
DRAWRAY draw a ray on the current axis
   drawRay(RAY)
   With RAY having the syntax: [x0 y0 dx dy], draws the ray starting from
   point (x0 y0) and going to direction (dx dy), clipped with the current
   window axis.
   drawRay(RAY, PARAMS, VALUE)
   Can specify param-pair values.
   H = drawRay(...)
   Returns handle on line object
   See also:
   rays2d, drawLine
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 31/10/2003.
CROSS-REFERENCE INFORMATION
This function calls:
intersectLines INTERSECTLINES return all intersection points of N lines in 2D
isPointOnRay ISPOINTONRAY test if a point belongs to a ray
onRay ONRAY test if a point belongs to a ray
This function is called by: