Description of polygonExpand
Home > imael > geom2d > polygonExpand.m
polygonExpand
PURPOSE
POLYGONEXPAND 'expand' a polygon with a given distance
SYNOPSIS
function poly2 = polygonExpand(polygon, dist)
DESCRIPTION
POLYGONEXPAND 'expand' a polygon with a given distance
   EXPOLY = polygonExpand(POLYGON, D);
   Associates each edge of POLYGON to an edge located at distance D, and
   computes polygon given by growing edges.
   This is a kind of dilatation, but behaviour on corners is different.
   This function keeps angles of polygons, but there is no direct relation
   between length of 2 polygons.
   It works fine for convex polygons, or for polygons whose complexity is
   not too high (self intersection of result polygon is not tested).
   It is also possible to specify negative distance, and get all points
   inside the polygon. If the polygon is convex, the result equals
   morphological erosion of polygon by a ball with radius equal to the
   given distance.
   See also:
   polygons2d
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 14/05/2005.
CROSS-REFERENCE INFORMATION
This function calls:
clipPolygonHP CLIPPOLYGONHP clip a polygon with a Half-plane defined by a directed line
createLine CREATELINE create a line with various inputs.
intersectLines INTERSECTLINES return all intersection points of N lines in 2D
parallelLine PARALLELLINE create a line parallel to another one.
This function is called by: