Description of polynomialCurveCurvatures
Home > imael > geom2d > polynomialCurveCurvatures.m
polynomialCurveCurvatures
PURPOSE
POLYNOMIALCURVECURVATURES compute curvatures of a polynomial revolution surface
SYNOPSIS
function varargout = polynomialCurveCurvatures(t, varargin)
DESCRIPTION
POLYNOMIALCURVECURVATURES compute curvatures of a polynomial revolution surface
   KAPPAS = polynomialCurveCurvatures(T, XCOEF, YCOEF)
   XCOEF and YCOEF are row vectors of coefficients, in the form:
       [a0 a1 a2 ... an]
   T is a column vector, containing the parametrization values for which
   curvatures have to be computed.
   KAPPAS is a matrix with 2 columns and as many rows as T, containing the
   2 main curvatures for each specified T.
   Curvatures are computed by assuming the curve to be rotated around the
   vertical axis (from point (0,0), in direction (1,0)).
   KAPPAS = polynomialCurveCurvatures(T, COEFS)
   COEFS is either a 2xN matrix (one row for the coefficients of each
   coordinate), or a cell array.
   [KAPPA1 KAPPA2] = polynomialCurveCurvatures(...)
   return the 2 main curvatures in separate arrays.
   ... = polynomialCurveCurvatures(..., AXIS)
   Specify the revolution axis. By default, revolution axis is the
   vertical axis, going through point (0,0) and having direction vector
   given by (0,1). Another axis of revolution can be specified in format:
   AXIS = [x0 y0 dx dy].
   See also
   polynomialCurves2d, polynomialCurveCurvature
 ------
 Author: David Legland
 e-mail: david.legland@nantes.inra.fr
 Created: 2007-02-23
 Copyright 2007 INRA - BIA PV Nantes - MIAJ Jouy-en-Josas.
 Licensed under the terms of the LGPL, see the file "license.txt"
CROSS-REFERENCE INFORMATION
This function calls:
lineAngle LINEANGLE return angle between lines
polynomialCurvePoint POLYNOMIALCURVEPOINT compute point corresponding to a position
polynomialDerivate POLYNOMIALDERIVATE derivate a polynomial
rotation ROTATION return 3*3 matrix of a rotation
transformPoint TRANSFORMPOINT transform a point with an affine transform
transformVector TRANSFORMVECTOR transform a vector with an affine transform
This function is called by: