Description of polygonSelfIntersections
Home > imael > geom2d > polygonSelfIntersections.m
polygonSelfIntersections
PURPOSE
POLYGONSELFINTERSECTIONS find common points between 2 polygons
SYNOPSIS
function varargout = polygonSelfIntersections(poly, varargin)
DESCRIPTION
POLYGONSELFINTERSECTIONS  find common points between 2 polygons
   PTS = polygonSelfIntersections(POLY)
   Return the position of self intersection points
   [PTS POS1 POS2] = polygonSelfIntersections(POLY)
   Also return the 2 positions of each intersection point (the position
   when meeting point for first time, then position when meeting point
   for the second time).
   Example
       % use a '8'-shaped polygon
       poly = [10 0;0 0;0 10;20 10;20 20;10 20];
       polygonSelfIntersections(poly)
       ans =
           10 10
   See also
   polygons2d, polylineSelfIntersections
 ------
 Author: David Legland
 e-mail: david.legland@grignon.inra.fr
 Created: 2009-06-15,    using Matlab 7.7.0.471 (R2008b)
 Copyright 2009 INRA - Cepia Software Platform.
 Licensed under the terms of the LGPL, see the file "license.txt"
CROSS-REFERENCE INFORMATION
This function calls:
distancePoints DISTANCEPOINTS compute distance between two points
polylineSelfIntersections POLYLINESELFINTERSECTIONS find self-intersections points of a polyline
This function is called by:
polygonLoops POLYGONLOOPS divide a possibly self-intersecting polygon into a set of simple loops