Description of polynomialCurveSetFit
Home > imael > geom2d > polynomialCurveSetFit.m
polynomialCurveSetFit
PURPOSE
POLYNOMIALCURVESETFIT fit a set of polynomial curves to a segmented image
SYNOPSIS
function varargout = polynomialCurveSetFit(seg, varargin)
DESCRIPTION
POLYNOMIALCURVESETFIT fit a set of polynomial curves to a segmented image
   COEFS = polynomialCurveSetFit(IMG);
   COEFS = polynomialCurveSetFit(IMG, DEG);
   Result is a cell array of matrices. Each matrix is DEG+1-by-2, and
   contains coefficients of polynomial curve for each coordinate.
   IMG is first binarised, then skeletonized. Each cure
   [COEFS LBL] = polynomialCurveSetFit(...);
   also returns an image of labels for the segmented curves. The max label
   is the number of curves, and the length of COEFS.
   Requires the toolboxes:
   - Optimization
   - Image Processing
   Example
   polynomialCurveSetFit
   See also
   polynomialCurves2d, polynomialCurveFit
 ------
 Author: David Legland
 e-mail: david.legland@nantes.inra.fr
 Created: 2007-03-21
 Copyright 2007 INRA - BIA PV Nantes - MIAJ Jouy-en-Josas.
 Licensed under the terms of the LGPL, see the file "license.txt"
CROSS-REFERENCE INFORMATION
This function calls:
minDistancePoints MINDISTANCEPOINTS compute minimal distance between several points
parametrize PARAMETRIZE return a parametrization of a curve
polynomialCurveFit POLYNOMIALCURVEFIT fit a polynomial curve to a series of points
This function is called by: