Description of polynomialDerivate
Home > imael > geom2d > polynomialDerivate.m
polynomialDerivate
PURPOSE
POLYNOMIALDERIVATE derivate a polynomial
SYNOPSIS
function deriv = polynomialDerivate(poly)
DESCRIPTION
POLYNOMIALDERIVATE derivate a polynomial
   DERIV = polynomialDERIVATE(POLY)
   POLY is a row vector of [n+1] coefficients, in the form:
       [a0 a1 a2 ... an]
   DERIV has the same format, with length n:
       [a1 a2*2 ... an*n]
   Example
   T = polynomialDerivate([2 3 4])
   returns:
   T = [3 8]
   See also
   polynomialCurves2d
 ------
 Author: David Legland
 e-mail: david.legland@nantes.inra.fr
 Created: 2007-02-23
 Copyright 2007 INRA - BIA PV Nantes - MIAJ Jouy-en-Josas.
 Licensed under the terms of the LGPL, see the file "license.txt"
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
polynomialCurveCentroid POLYNOMIALCURVECENTROID compute the centroid of a polynomial curve
polynomialCurveCurvature POLYNOMIALCURVECURVATURE compute the local curvature of a polynomial curve
polynomialCurveCurvatures POLYNOMIALCURVECURVATURES compute curvatures of a polynomial revolution surface
polynomialCurveDerivative POLYNOMIALCURVEDERIVATIVE compute derivative vector of a polynomial curve
polynomialCurveLength POLYNOMIALCURVELENGTH compute the length of a polynomial curve
polynomialCurvePosition POLYNOMIALCURVEPOSITION compute position on a curve for a given length