Description of circle3dOrigin
Home > imael > geom3d > circle3dOrigin.m
circle3dOrigin
PURPOSE
CIRCLE3DORIGIN return the first point of a 3D circle
SYNOPSIS
function ori = circle3dOrigin(varargin)
DESCRIPTION
CIRCLE3DORIGIN return the first point of a 3D circle
   P = circle3dOrigin([XC YC ZC R THETA PHI])
   P = circle3dOrigin([XC YC ZC R THETA PHI PSI])
   Returns the origin point of the circle, i.e. the first point used for
   drawing circle.
   See also:
   circles3d, points3d
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 21/02/2005
CROSS-REFERENCE INFORMATION
This function calls:
localToGlobal3d LOCALTOGLOBAL3D create transform from a vector and 3 rotation angles
transformPoint3d TRANSFORMPOINT3D transform a point with a 3D affine transform
This function is called by:
circle3dPosition CIRCLE3DPOSITION return the angular position of a point on a 3D circle