Description of drawCircle3d
Home > imael > geom3d > drawCircle3d.m
drawCircle3d
PURPOSE
DRAWCIRCLE3D draw a 3D circle
SYNOPSIS
function varargout = drawCircle3d(varargin)
DESCRIPTION
DRAWCIRCLE3D draw a 3D circle
   Possible calls for the function :
   drawCircle3d([XC YC ZC R THETA PHI])
   drawCircle3d([XC YC ZC R THETA PHI PSI])
   drawCircle3d([XC YC ZC R], [THETA PHI])
   drawCircle3d([XC YC ZC R], [THETA PHI PSI])
   drawCircle3d([XC YC ZC R], THETA, PHI)
   drawCircle3d([XC YC ZC], R, THETA, PHI)
   drawCircle3d([XC YC ZC R], THETA, PHI, PSI)
   drawCircle3d([XC YC ZC], R, THETA, PHI, PSI)
   drawCircle3d(XC, YC, ZC, R, THETA, PHI)
   drawCircle3d(XC, YC, ZC, R, THETA, PHI, PSI)
   where XC, YC, ZY are coordinate of circle center, R is the radius of he
   circle, PHI and THETA are 3D angle of the normal to the plane
   containing the circle (PHI between 0 and 2xPI corresponding to
   longitude, and THETA from 0 to PI, corresponding to angle with
   vertical).
   H = drawCircle3d(...)
   return handle on the created LINE object
   See also:
   circles3d
   ------
   Author: David Legland
   e-mail: david.legland@jouy.inra.fr
   Created: 2005-02-17
   Copyright 2005 INRA - CEPIA Nantes - MIAJ (Jouy-en-Josas).
CROSS-REFERENCE INFORMATION
This function calls:
drawCurve3d DRAWCURVE3D draw a 3D curve specified by a list of points
localToGlobal3d LOCALTOGLOBAL3D create transform from a vector and 3 rotation angles
transformPoint3d TRANSFORMPOINT3D transform a point with a 3D affine transform
This function is called by: