Description of drawSphericalTriangle
Home > imael > geom3d > drawSphericalTriangle.m
drawSphericalTriangle
PURPOSE
DRAWSPHERICALTRIANGLE draw a triangle on a sphere
SYNOPSIS
function varargout = drawSphericalTriangle(sphere, p1, p2, p3, varargin)
DESCRIPTION
DRAWSPHERICALTRIANGLE draw a triangle on a sphere
   drawsphericaltriangle(SPHERE, PT1, PT2, PT3);
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 22/02/2005
CROSS-REFERENCE INFORMATION
This function calls:
createPlane CREATEPLANE create a plane in parametrized form
intersectLinePlane INTERSECTLINEPLANE return intersection between a plane and a line
normalizeVector3d NORMALIZEVECTOR3D normalize a 3D vector
planePosition PLANEPOSITION compute position of a point on a plane
This function is called by: