Description of drawCurve3d
Home > imael > geom3d > drawCurve3d.m
drawCurve3d
PURPOSE
DRAWCURVE3D draw a 3D curve specified by a list of points
SYNOPSIS
function varargout = drawCurve3d(varargin)
DESCRIPTION
DRAWCURVE3D draw a 3D curve specified by a list of points
   drawCurve3d(COORD) packs coordinates in a single [N*3] array.
   drawCurve3d(PX, PY, PZ) specify coordinates in separate arrays.
   H = drawCurve3d(...) also return a handle to the list of line objects.
   See Also :
   drawPolygon
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 18/02/2005.
CROSS-REFERENCE INFORMATION
This function calls:
drawCurve3d DRAWCURVE3D draw a 3D curve specified by a list of points
This function is called by:
drawCircle3d DRAWCIRCLE3D draw a 3D circle
drawCircleArc3d DRAWCIRCLEARC3D draw a 3D circle arc
drawCurve3d DRAWCURVE3D draw a 3D curve specified by a list of points
drawEllipse3d DRAWELLIPSE3D draw a 3D ellipse
drawPartialPatch drawSurfPatch : draw surface patch, with 2 parametrized surfaces
drawSurfPatch DRAWSURFPATCH draw surface patch, with 2 parametrized surfaces