Description of localToGlobal3d
Home > imael > geom3d > localToGlobal3d.m
localToGlobal3d
PURPOSE
LOCALTOGLOBAL3D create transform from a vector and 3 rotation angles
SYNOPSIS
function trans = localToGlobal3d(varargin)
DESCRIPTION
LOCALTOGLOBAL3D  create transform from a vector and 3 rotation angles
   TRANS = localToGlobal3d(CENTER, THETA, PHI, PSI)
   Example
   localToGlobal3d
   See also
   transforms3d
 ------
 Author: David Legland
 e-mail: david.legland@grignon.inra.fr
 Created: 2009-06-19,    using Matlab 7.7.0.471 (R2008b)
 Copyright 2009 INRA - Cepia Software Platform.
CROSS-REFERENCE INFORMATION
This function calls:
createRotationOy CREATEROTATIONOY return 4x4 matrix of a rotation around y-axis
createRotationOz CREATEROTATIONOZ return 4x4 matrix of a rotation around z-axis
createTranslation3d CREATETRANSLATION3D return 4x4 matrix of a 3D translation
This function is called by:
circle3dOrigin CIRCLE3DORIGIN return the first point of a 3D circle
drawCircle3d DRAWCIRCLE3D draw a 3D circle
drawCircleArc3d DRAWCIRCLEARC3D draw a 3D circle arc
drawCylinder DRAWCYLINDER draw a cylinder
drawEllipse3d DRAWELLIPSE3D draw a 3D ellipse