Description of meshReduce
Home > imael > geom3d > meshReduce.m
meshReduce
PURPOSE
MESHREDUCE return mesh with minimal number of faces
SYNOPSIS
function varargout = meshReduce(nodes, varargin)
DESCRIPTION
MESHREDUCE return mesh with minimal number of faces
   [NODES FACES] = meshReduce(NODES, FACES)
   [NODES EDGES FACES] = meshReduce(NODES, EDGES, FACES)
   NODES is a set of 3D points (as a Nn-by-3 array),
   and FACES is one of:
   - a Nf-by-X array containing vertex indices of each face, with each
   face having the same number of vertices,
   - a Nf-by 1 cell array, each cell containing indices of a face.
   The function groups faces which are coplanar and contiguous, resulting
   in a "lighter" mesh. This can be useful to visualize binary 3D images
   for example.
   FACES = meshReduce(..., PRECISION)
   Adjust the threshold for deciding if two faces are coplanar or
   parallel. Default value is 1e-14.
   Example
   [n e f] = createCube;
   f2 = meshReduce(n);
   drawPolyhedra(n, f);
   See also
   drawPolyhedra, convhull, convhulln, minConvexHull
 ------
 Author: David Legland
 e-mail: david.legland@jouy.inra.fr
 Created: 2006-07-05
 Copyright 2006 INRA - CEPIA Nantes - MIAJ (Jouy-en-Josas).
CROSS-REFERENCE INFORMATION
This function calls:
faceNormal FACENORMAL compute normal vector of a polyhedron face
isCoplanar ISCOPLANAR Tests input points for coplanarity in 3-space.
vectorNorm3d VECTORNORM3D compute norm of vector or of set of 3D vectors
This function is called by: