Description of createTranslation3d
Home > matGeom > geom3d > createTranslation3d.m
createTranslation3d
PURPOSE
CREATETRANSLATION3D Create the 4x4 matrix of a 3D translation.
SYNOPSIS
function trans = createTranslation3d(varargin)
DESCRIPTION
CREATETRANSLATION3D Create the 4x4 matrix of a 3D translation.
   usage:
   TRANS = createTranslation3d(DX, DY, DZ);
   return the translation corresponding to DX and DY.
   The returned matrix has the form :
   [1 0 0 DX]
   [0 1 0 DY]
   [0 0 1 DZ]
   [0 0 0  1]
   TRANS = createTranslation3d(VECT);
   return the translation corresponding to the given vector [x y z].
   See also:
   transforms3d, transformPoint3d, transformVector3d,
   createRotationOx, createRotationOy, createRotationOz, createScaling3d
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 06/04/2004.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
createRotationAboutPoint3d CREATEROTATIONABOUTPOINT3D Rotate about a point using a rotation matrix.
drawCube Draw a 3D centered cube, eventually rotated.
drawCuboid Draw a 3D cuboid, eventually rotated.
drawEllipsoid DRAWELLIPSOID Draw a 3D ellipsoid.
geodesicCylinder GEODESICCYLINDER computes the geodesic between two points on a cylinder.
projPointOnCylinder PROJPOINTONCYLINDER Project a 3D point onto a cylinder.
recenterTransform3d RECENTERTRANSFORM3D Change the fixed point of an affine 3D transform.
curveToMesh Create a mesh surrounding a 3D curve.
ellipsoidMesh ELLIPSOIDMESH Convert a 3D ellipsoid to face-vertex mesh representation.
triangulatePolygonPair Compute triangulation between a pair of 3D closed curves.
SOURCE CODE
function trans = createTranslation3d(varargin)
%CREATETRANSLATION3D Create the 4x4 matrix of a 3D translation.
%
%   usage:
%   TRANS = createTranslation3d(DX, DY, DZ);
%   return the translation corresponding to DX and DY.
%   The returned matrix has the form :
%   [1 0 0 DX]
%   [0 1 0 DY]
%   [0 0 1 DZ]
%   [0 0 0  1]
%
%   TRANS = createTranslation3d(VECT);
%   return the translation corresponding to the given vector [x y z].
%
%
%   See also:
%   transforms3d, transformPoint3d, transformVector3d,
%   createRotationOx, createRotationOy, createRotationOz, createScaling3d
%
%   ---------
%
%   author : David Legland
%   INRA - TPV URPOI - BIA IMASTE
%   created the 06/04/2004.
%
%   HISTORY
%   22/04/2009 rename as createTranslation3d
if isempty(varargin)
    % assert translation with null vector
    dx = 0;
    dy = 0;
    dz = 0;
elseif length(varargin)==1
    % translation vector given in a single argument
    var = varargin{1};
    dx = var(1);
    dy = var(2);
    dz = var(3);
else
    % translation vector given in 3 arguments
    dx = varargin{1};
    dy = varargin{2};
    dz = varargin{3};
end
% create the translation matrix
trans = [1 0 0 dx ; 0 1 0 dy ; 0 0 1 dz; 0 0 0 1];