Description of createRotationVector3d
Home > matGeom > geom3d > createRotationVector3d.m
createRotationVector3d
PURPOSE
CREATEROTATIONVECTOR3D Calculates the rotation between two vectors.
SYNOPSIS
function ROT = createRotationVector3d(A,B)
DESCRIPTION
CREATEROTATIONVECTOR3D Calculates the rotation between two vectors.
   ROT = createRotationVector3d(A, B) returns the 4x4 rotation matrix ROT
   to transform vector A in the same direction as vector B.
   Example
     A=[ .1  .2  .3];
     B=-1+2.*rand(1,3);
     ROT = createRotationVector3d(A,B);
     C = transformVector3d(A,ROT);
     figure('color','w'); hold on; view(3)
     O=[0 0 0];
     drawVector3d(O, A,'r');
     drawVector3d(O, B,'g');
     drawVector3d(O, C,'r');
   See also
   transformPoint3d, createRotationOx, createRotationOy, createRotationOz
   Source
     https://math.stackexchange.com/a/897677
 ---------
 Author: oqilipo
 Created: 2017-08-07
 Copyright 2017
CROSS-REFERENCE INFORMATION
This function calls:
isParallel3d ISPARALLEL3D Check parallelism of two 3D vectors.
normalizeVector3d NORMALIZEVECTOR3D Normalize a 3D vector to have norm equal to 1.
This function is called by:
createRotationVectorPoint3d CREATEROTATIONVECTORPOINT3D Calculates the rotation between two vectors.
drawAngleBetweenVectors3d DRAWANGLEBETWEENVECTORS3D Draw an arc between 2 vectors.
drawArrow3d DRAWARROW3D plot a quiver of 3D arrows.
geodesicCylinder GEODESICCYLINDER computes the geodesic between two points on a cylinder.
projPointOnCylinder PROJPOINTONCYLINDER Project a 3D point onto a cylinder.
SOURCE CODE
function ROT = createRotationVector3d(A,B)
%CREATEROTATIONVECTOR3D Calculates the rotation between two vectors.
%
%   ROT = createRotationVector3d(A, B) returns the 4x4 rotation matrix ROT
%   to transform vector A in the same direction as vector B.
%
%   Example
%     A=[ .1  .2  .3];
%     B=-1+2.*rand(1,3);
%     ROT = createRotationVector3d(A,B);
%     C = transformVector3d(A,ROT);
%     figure('color','w'); hold on; view(3)
%     O=[0 0 0];
%     drawVector3d(O, A,'r');
%     drawVector3d(O, B,'g');
%     drawVector3d(O, C,'r');
%
%   See also
%   transformPoint3d, createRotationOx, createRotationOy, createRotationOz
%
%   Source
%     https://math.stackexchange.com/a/897677
%
% ---------
% Author: oqilipo
% Created: 2017-08-07
% Copyright 2017
if isParallel3d(A,B)
    if A*B'>0
        ROT = eye(4);
    else
        ROT = -1*eye(4); ROT(end)=1;
    end
else
    a=normalizeVector3d(A);
    b=normalizeVector3d(B);
    a=reshape(a,3,1);
    b=reshape(b,3,1);
    v = cross(a,b);
    ssc = [0 -v(3) v(2); v(3) 0 -v(1); -v(2) v(1) 0];
    ROT = eye(3) + ssc + ssc^2*(1-dot(a,b))/(norm(v))^2;
    ROT = [ROT, [0;0;0]; 0 0 0 1];
end
end