Description of crossProduct3d
Home > matGeom > geom3d > crossProduct3d.m
crossProduct3d
PURPOSE
CROSSPRODUCT3D Vector cross product faster than inbuilt MATLAB cross.
SYNOPSIS
function c = crossProduct3d(a,b)
DESCRIPTION
CROSSPRODUCT3D Vector cross product faster than inbuilt MATLAB cross.
   C = crossProduct3d(A, B)
   returns the cross product of the two 3D vectors A and B, that is:
       C = A x B
   A and B must be N-by-3 element vectors. If either A or B is a 1-by-3
   row vector, the result C will have the size of the other input and will
   be the  concatenation of each row's cross product.
   Example
     v1 = [2 0 0];
     v2 = [0 3 0];
     crossProduct3d(v1, v2)
     ans =
         0   0   6
   Class support for inputs A,B:
      float: double, single
   See also DOT.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
createBasisTransform3d CREATEBASISTRANSFORM3D Compute matrix for transforming a basis into another basis.
distancePointLine3d DISTANCEPOINTLINE3D Euclidean distance between 3D point and line.
drawAngleBetweenVectors3d DRAWANGLEBETWEENVECTORS3D Draw an arc between 2 vectors.
intersectLinePlane INTERSECTLINEPLANE Intersection point between a 3D line and a plane.
isParallel3d ISPARALLEL3D Check parallelism of two 3D vectors.
isPointOnLine3d ISPOINTONLINE3D Test if a 3D point belongs to a 3D line.
normalizePlane NORMALIZEPLANE Normalize parametric representation of a plane.
orientedBox3d Object-oriented bounding box of a set of 3D points.
planeNormal PLANENORMAL Compute the normal to a plane.
projPointOnPlane PROJPOINTONPLANE Return the orthogonal projection of a point on a plane.
vectorAngle3d VECTORANGLE3D Angle between two 3D vectors.
intersectLineMesh3d Intersection points of a 3D line with a mesh.
mergeCoplanarFaces MERGECOPLANARFACES Merge coplanar faces of a polyhedral mesh.
meshCurvatures Compute principal curvatures on mesh vertices.
meshFaceAreas MESHFACEAREAS Surface area of each face of a mesh.
trimeshSurfaceArea TRIMESHSURFACEAREA Surface area of a triangular mesh.
SOURCE CODE
function c = crossProduct3d(a,b)
%CROSSPRODUCT3D Vector cross product faster than inbuilt MATLAB cross.
%
%   C = crossProduct3d(A, B)
%   returns the cross product of the two 3D vectors A and B, that is:
%       C = A x B
%   A and B must be N-by-3 element vectors. If either A or B is a 1-by-3
%   row vector, the result C will have the size of the other input and will
%   be the  concatenation of each row's cross product.
%
%   Example
%     v1 = [2 0 0];
%     v2 = [0 3 0];
%     crossProduct3d(v1, v2)
%     ans =
%         0   0   6
%
%
%   Class support for inputs A,B:
%      float: double, single
%
%   See also DOT.
%   Sven Holcombe
% HISTORY
% 2017-11-24 rename from vectorCross3d to crossProduct3d
% size of inputs
sizeA = size(a);
sizeB = size(b);
% Initialise c to the size of a or b, whichever has more dimensions. If
% they have the same dimensions, initialise to the larger of the two
switch sign(numel(sizeA) - numel(sizeB))
    case 1
        c = zeros(sizeA);
    case -1
        c = zeros(sizeB);
    otherwise
        c = zeros(max(sizeA, sizeB));
end
c(:) = bsxfun(@times, a(:,[2 3 1],:), b(:,[3 1 2],:)) - ...
       bsxfun(@times, b(:,[2 3 1],:), a(:,[3 1 2],:));