Description of distancePoints3d
Home > matGeom > geom3d > distancePoints3d.m
distancePoints3d
PURPOSE
DISTANCEPOINTS3D Compute euclidean distance between pairs of 3D Points.
SYNOPSIS
function dist = distancePoints3d(p1, p2, varargin)
DESCRIPTION
DISTANCEPOINTS3D Compute euclidean distance between pairs of 3D Points.
   D = distancePoints3d(P1, P2) return distance between points P1 and
   P2, given as [X Y Z].
   If P1 and P2 are two arrays of points, result is a N1*N2 array
   containing distance between each point of P1 and each point of P2.
   D = distancePoints3d(P1, P2, NOR)
   with NOR being 1, 2, or Inf, corresponfing to the norm used. Default is
   2 (euclidean norm). 1 correspond to manhattan (or taxi driver) distance
   and Inf to maximum difference in each coordinate.
   See also
   points3d, minDistancePoints, distancePoints
CROSS-REFERENCE INFORMATION
This function calls:
vectorNorm3d VECTORNORM3D Norm of a 3D vector or of set of 3D vectors.
This function is called by:
clipPoints3d CLIPPOINTS3D Clip a set of points by a box or other 3d shapes.
cylinderSurfaceArea CYLINDERSURFACEAREA Surface area of a cylinder.
distancePointCircle3d DISTANCEPOINTCIRCLE3D Distance between 3D points and 3D circle.
intersectPlaneSphere INTERSECTPLANESPHERE Return intersection circle between a plane and a sphere.
projPointOnCircle3d PROJPOINTONCIRCLE3D Project a 3D point onto a 3D circle.
projPointOnCylinder PROJPOINTONCYLINDER Project a 3D point onto a cylinder.
meshVoronoiDiagram MESHVORONOIDIAGRAM Voronoi Diagram on the surface of a polygonal mesh.
triangulatePolygonPair3d TRIANGULATEPOLYGONPAIR3D Compute a triangulation between a pair of 3D polygons.
SOURCE CODE
function dist = distancePoints3d(p1, p2, varargin)
%DISTANCEPOINTS3D Compute euclidean distance between pairs of 3D Points.
%
%   D = distancePoints3d(P1, P2) return distance between points P1 and
%   P2, given as [X Y Z].
%
%   If P1 and P2 are two arrays of points, result is a N1*N2 array
%   containing distance between each point of P1 and each point of P2.
%
%
%   D = distancePoints3d(P1, P2, NOR)
%   with NOR being 1, 2, or Inf, corresponfing to the norm used. Default is
%   2 (euclidean norm). 1 correspond to manhattan (or taxi driver) distance
%   and Inf to maximum difference in each coordinate.
%
%
%   See also
%   points3d, minDistancePoints, distancePoints
% ------
% Author: David Legland
% E-mail: david.legland@inrae.fr
% Created: 2005-02-18
% Copyright 2005-2024 INRA - TPV URPOI - BIA IMASTE
norm = 2;
if isscalar(varargin)
    norm = varargin{1};
end
% compute difference of coordinate for each pair of points
ptsDiff = bsxfun(@minus, p2, p1);
% Return dist based on the type of measurement requested
switch(norm)
    case 1
        dist = sum(abs(ptsDiff),2);
    case 2
        dist = vectorNorm3d(ptsDiff);
    case Inf
        dist = max(abs(ptsDiff), [], 2);
    otherwise
        dist = power(sum(power(ptsDiff, norm),2), 1/norm);
end