Description of isPlane
Home > matGeom > geom3d > isPlane.m
isPlane
PURPOSE
ISPLANE Check if input is a plane.
SYNOPSIS
function d = isPlane(plane)
DESCRIPTION
ISPLANE Check if input is a plane.
   B = isPlane(PLANE) where PLANE should be a plane or multiple planes
   Example
     isPlane([...
         0 0 0 1 0 0 0 1 0;...
         0 0 0 1 0 0 -1 0 0;...
         0 0 0 1i 0 0 -1 0 0;...
         0 0 0 nan 0 0 0 1 0;...
         0 0 0 inf 0 0 0 1 0])
   See also
   createPlane3d
 ------
 Author: oqilipo
 Created: 2017-07-09
 Copyright 2017
CROSS-REFERENCE INFORMATION
This function calls:
isParallel3d ISPARALLEL3D Check parallelism of two 3D vectors.
This function is called by:
drawPlane3d Draw a plane clipped by the current axes.
drawPlatform DRAWPLATFORM Draw a rectangular platform with a given size.
cutMeshByPlane CUTMESHBYPLANE Cut a mesh by a plane.
meshSilhouette MESHSILHOUETTE Compute the 2D outline of a 3D mesh on an arbitrary plane.
SOURCE CODE
function d = isPlane(plane)
%ISPLANE Check if input is a plane.
%
%   B = isPlane(PLANE) where PLANE should be a plane or multiple planes
%
%   Example
%     isPlane([...
%         0 0 0 1 0 0 0 1 0;...
%         0 0 0 1 0 0 -1 0 0;...
%         0 0 0 1i 0 0 -1 0 0;...
%         0 0 0 nan 0 0 0 1 0;...
%         0 0 0 inf 0 0 0 1 0])
%
%   See also
%   createPlane3d
%
% ------
% Author: oqilipo
% Created: 2017-07-09
% Copyright 2017
narginchk(1,1)
if size(plane,2)~=9
    d=false(size(plane,1),1);
    return
end
a = ~any(isnan(plane),2);
b = ~any(isinf(plane),2);
c = ~isParallel3d(plane(:,4:6), plane(:,7:9));
d = a & b & c;
end