Description of isPointOnLine3d
Home > matGeom > geom3d > isPointOnLine3d.m
isPointOnLine3d
PURPOSE
ISPOINTONLINE3D Test if a 3D point belongs to a 3D line.
SYNOPSIS
function b = isPointOnLine3d(point, line, varargin)
DESCRIPTION
ISPOINTONLINE3D Test if a 3D point belongs to a 3D line.
   B = isPointOnLine3d(POINT, LINE)
   with POINT being [xp yp zp], and LINE being [x0 y0 z0 dx dy dz].
   Returns 1 if point lies on the line, 0 otherwise.
   If POINT is an N-by-3 array of points, B is a N-by-1 array of booleans.
   If LINE is a N-by-6 array of lines, B is a N-by-1 array of booleans.
   B = isPointOnLine3d(POINT, LINE, TOL)
   Specifies the tolerance used for testing location on 3D line.
   See also:
   lines3d, distancePointLine3d, linePosition3d, isPointOnLine
CROSS-REFERENCE INFORMATION
This function calls:
crossProduct3d CROSSPRODUCT3D Vector cross product faster than inbuilt MATLAB cross.
vectorNorm3d VECTORNORM3D Norm of a 3D vector or of set of 3D vectors.
This function is called by:
isPointOnEdge3d Test if a 3D point belongs to an edge.
SOURCE CODE
function b = isPointOnLine3d(point, line, varargin)
%ISPOINTONLINE3D Test if a 3D point belongs to a 3D line.
%
%   B = isPointOnLine3d(POINT, LINE)
%   with POINT being [xp yp zp], and LINE being [x0 y0 z0 dx dy dz].
%   Returns 1 if point lies on the line, 0 otherwise.
%
%   If POINT is an N-by-3 array of points, B is a N-by-1 array of booleans.
%
%   If LINE is a N-by-6 array of lines, B is a N-by-1 array of booleans.
%
%   B = isPointOnLine3d(POINT, LINE, TOL)
%   Specifies the tolerance used for testing location on 3D line.
%
%   See also:
%   lines3d, distancePointLine3d, linePosition3d, isPointOnLine
%
% ---------
% author : David Legland
% e-mail: david.legland@inra.fr
% INRA - TPV URPOI - BIA IMASTE
% created the 31/10/2003.
%
%   HISTORY
%   17/12/2013 create from isPointOnLine
% extract computation tolerance
tol = 1e-14;
if ~isempty(varargin)
    tol = varargin{1};
end
% size of inputs
np = size(point,1);
nl = size(line, 1);
if np == 1 || nl == 1 || np == nl
    % test if lines are colinear, using norm of the cross product
    b = bsxfun(@rdivide, vectorNorm3d( ...
        crossProduct3d(bsxfun(@minus, line(:,1:3), point), line(:,4:6))), ...
        vectorNorm3d(line(:,4:6))) < tol;
else
    % same test, but after reshaping arrays to manage difference of
    % dimensionality
    point = reshape(point, [np 1 3]);
    line = reshape(line, [1 nl 6]);
    b = bsxfun(@rdivide, vectorNorm3d( ...
        cross(bsxfun(@minus, line(:,:,1:3), point), line(ones(1,np),:,4:6), 3)), ...
        vectorNorm3d(line(:,:,4:6))) < tol;
end