Description of normalizeVector3d
Home > matGeom > geom3d > normalizeVector3d.m
normalizeVector3d
PURPOSE
NORMALIZEVECTOR3D Normalize a 3D vector to have norm equal to 1.
SYNOPSIS
function vn = normalizeVector3d(v)
DESCRIPTION
NORMALIZEVECTOR3D Normalize a 3D vector to have norm equal to 1.
   V2 = normalizeVector3d(V);
   Returns the normalization of vector V, such that ||V|| = 1. Vector V is
   given as a row vector.
   If V is a N-by-3 array, normalization is performed for each row of the
   input array.
   If V is a M-by-N-by-3 array, normalization is performed along the last
   dimension of the array.
   See also:
     vectors3d, vectorNorm3d
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
anglePoints3d ANGLEPOINTS3D Compute angle between three 3D points.
createPlane CREATEPLANE Create a plane in parametrized form.
createRotation3dLineAngle CREATEROTATION3DLINEANGLE Create rotation around a line by an angle theta.
createRotationVector3d CREATEROTATIONVECTOR3D Calculates the rotation between two vectors.
distancePointPlane DISTANCEPOINTPLANE Signed distance betwen 3D point and plane.
drawAngleBetweenVectors3d DRAWANGLEBETWEENVECTORS3D Draw an arc between 2 vectors.
drawSphericalTriangle DRAWSPHERICALTRIANGLE Draw a triangle on a sphere.
fillSphericalTriangle FILLSPHERICALTRIANGLE Fill a triangle on a sphere.
intersectPlanes INTERSECTPLANES Return intersection line between 2 planes in space.
intersectThreePlanes INTERSECTTHREEPLANES Return intersection point between 3 planes in space.
normalizeLine3d NORMALIZELINE3D Normalizes the direction vector of a 3D line.
normalizePlane NORMALIZEPLANE Normalize parametric representation of a plane.
orientedBox3d Object-oriented bounding box of a set of 3D points.
parallelPlane PARALLELPLANE Parallel to a plane through a point or at a given distance.
projPointOnCircle3d PROJPOINTONCIRCLE3D Project a 3D point onto a 3D circle.
sphericalAngle SPHERICALANGLE Compute angle between points on the sphere.
curveToMesh Create a mesh surrounding a 3D curve.
meshFaceNormals MESHFACENORMALS Compute normal vector of faces in a 3D mesh.
meshSurfaceArea Surface area of a polyhedral mesh.
meshVertexNormals MESHVERTEXNORMALS Compute normals to a mesh vertices.
vertexNormal VERTEXNORMAL Compute normals to a mesh vertices.
SOURCE CODE
function vn = normalizeVector3d(v)
%NORMALIZEVECTOR3D Normalize a 3D vector to have norm equal to 1.
%
%   V2 = normalizeVector3d(V);
%   Returns the normalization of vector V, such that ||V|| = 1. Vector V is
%   given as a row vector.
%
%   If V is a N-by-3 array, normalization is performed for each row of the
%   input array.
%
%   If V is a M-by-N-by-3 array, normalization is performed along the last
%   dimension of the array.
%
%   See also:
%     vectors3d, vectorNorm3d
%
%   ---------
%   author : David Legland
%   INRA - TPV URPOI - BIA IMASTE
%   created the 29/11/2004.
%
% HISTORY
% 2005-11-30 correct a bug
% 2009-06-19 rename as normalizeVector3d
% 2010-11-16 use bsxfun (Thanks to Sven Holcombe)
if ismatrix(v)
    vn = bsxfun(@rdivide, v, sqrt(sum(v.^2, 2)));
else
    vn = bsxfun(@rdivide, v, sqrt(sum(v.^2, ndims(v))));
end