Description of planeNormal
Home > matGeom > geom3d > planeNormal.m
planeNormal
PURPOSE
PLANENORMAL Compute the normal to a plane.
SYNOPSIS
function n = planeNormal(plane)
DESCRIPTION
PLANENORMAL Compute the normal to a plane.
   N = planeNormal(PLANE)
   compute the normal of the given plane
   PLANE : [x0 y0 z0 dx1 dy1 dz1 dx2 dy2 dz2]
   N : [dx dy dz]
   See also
   geom3d, planes3d, createPlane
CROSS-REFERENCE INFORMATION
This function calls:
crossProduct3d CROSSPRODUCT3D Vector cross product faster than inbuilt MATLAB cross.
This function is called by:
dihedralAngle DIHEDRALANGLE Compute dihedral angle between 2 planes.
intersectPlaneSphere INTERSECTPLANESPHERE Return intersection circle between a plane and a sphere.
isBelowPlane ISBELOWPLANE Test whether a point is below or above a plane.
normalizePlane NORMALIZEPLANE Normalize parametric representation of a plane.
parallelPlane PARALLELPLANE Parallel to a plane through a point or at a given distance.
planesBisector PLANESBISECTOR Bisector plane between two other planes.
clipConvexPolyhedronHP CLIPCONVEXPOLYHEDRONHP Clip a convex polyhedron by a plane.
meshSilhouette MESHSILHOUETTE Compute the 2D outline of a 3D mesh on an arbitrary plane.
minConvexHull MINCONVEXHULL Return the unique minimal convex hull of a set of 3D points.
SOURCE CODE
function n = planeNormal(plane)
%PLANENORMAL Compute the normal to a plane.
%
%   N = planeNormal(PLANE)
%   compute the normal of the given plane
%   PLANE : [x0 y0 z0 dx1 dy1 dz1 dx2 dy2 dz2]
%   N : [dx dy dz]
%
%   See also
%   geom3d, planes3d, createPlane
%
%   ---------
%   author : David Legland
%   INRA - TPV URPOI - BIA IMASTE
%   created the 17/02/2005.
%
%   HISTORY
%   15/04/2013 Extended to N-dim planes by Sven Holcombe
% plane normal
outSz = size(plane);
outSz(2) = 3;
n = zeros(outSz);
n(:) = crossProduct3d(plane(:,4:6,:), plane(:, 7:9,:));