Description of vectorNorm3d
Home > matGeom > geom3d > vectorNorm3d.m
vectorNorm3d
PURPOSE
VECTORNORM3D Norm of a 3D vector or of set of 3D vectors.
SYNOPSIS
function n = vectorNorm3d(v)
DESCRIPTION
VECTORNORM3D Norm of a 3D vector or of set of 3D vectors.
   N = vectorNorm3d(V);
   Returns the norm of vector V.
   When V is a N-by-3 array, compute norm for each vector of the array.
   Vectors are given as rows. Result is then a N-by-1 array.
   NOTE: Computes only the Euclidean norm.
   See also:
     vectors3d, normalizeVector3d, vectorAngle3d, hypot3
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
createPlane CREATEPLANE Create a plane in parametrized form.
dihedralAngle DIHEDRALANGLE Compute dihedral angle between 2 planes.
distanceLines3d DISTANCELINES3D Minimal distance between two 3D lines.
distancePointLine3d DISTANCEPOINTLINE3D Euclidean distance between 3D point and line.
distancePoints3d DISTANCEPOINTS3D Compute euclidean distance between pairs of 3D Points.
intersectLineTriangle3d INTERSECTLINETRIANGLE3D Intersection point of a 3D line and a 3D triangle.
isParallel3d ISPARALLEL3D Check parallelism of two 3D vectors.
isPointOnLine3d ISPOINTONLINE3D Test if a 3D point belongs to a 3D line.
planePosition PLANEPOSITION Compute position of a point on a plane.
polygonArea3d POLYGONAREA3D Area of a 3D polygon.
triangleArea3d TRIANGLEAREA3D Area of a 3D triangle.
vectorAngle3d VECTORANGLE3D Angle between two 3D vectors.
intersectLineMesh3d Intersection points of a 3D line with a mesh.
mergeCoplanarFaces MERGECOPLANARFACES Merge coplanar faces of a polyhedral mesh.
meshFaceAreas MESHFACEAREAS Surface area of each face of a mesh.
meshSilhouette MESHSILHOUETTE Compute the 2D outline of a 3D mesh on an arbitrary plane.
minConvexHull MINCONVEXHULL Return the unique minimal convex hull of a set of 3D points.
trimeshSurfaceArea TRIMESHSURFACEAREA Surface area of a triangular mesh.
SOURCE CODE
function n = vectorNorm3d(v)
%VECTORNORM3D Norm of a 3D vector or of set of 3D vectors.
%
%   N = vectorNorm3d(V);
%   Returns the norm of vector V.
%
%   When V is a N-by-3 array, compute norm for each vector of the array.
%   Vectors are given as rows. Result is then a N-by-1 array.
%
%   NOTE: Computes only the Euclidean norm.
%
%   See also:
%     vectors3d, normalizeVector3d, vectorAngle3d, hypot3
%
%   ---------
%   author : David Legland
%   INRA - TPV URPOI - BIA IMASTE
%   created the 21/02/2005.
%   HISTORY
%   19/06/2009 rename as vectorNorm3d
n = sqrt(sum(v.*v, ndims(v)));