Description of meshEdges
Home > matGeom > meshes3d > meshEdges.m
meshEdges
PURPOSE
MESHEDGES Computes array of edge vertex indices from face array.
SYNOPSIS
function edges = meshEdges(faces, varargin)
DESCRIPTION
MESHEDGES Computes array of edge vertex indices from face array.
   EDGES = meshEdges(FACES);
   Example
     meshEdges
   See also
     meshes3d, meshEdgeFaces, meshFaceEdges
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
checkMeshAdjacentFaces CHECKMESHADJACENTFACES Check if adjacent faces of a mesh have similar orientation.
collapseEdgesWithManyFaces removes mesh edges adjacent to more than two faces
createDurerPolyhedron CREATEDURERPOLYHEDRON Create a mesh representing Durer's polyhedron .
intersectPlaneMesh Compute the polygons resulting from plane-mesh intersection.
isManifoldMesh ISMANIFOLDMESH Check whether the input mesh may be considered as manifold.
meshBoundary MESHBOUNDARY Boundary of a mesh as a collection of 3D line strings.
meshBoundaryEdgeIndices MESHBOUNDARYEDGEINDICES Indices of boundary edges of a mesh.
meshBoundaryVertexIndices MESHBOUNDARYVERTEXINDICES Indices of boundary vertices of a mesh.
removeInvalidBorderFaces REMOVEINVALIDBORDERFACES Remove faces whose edges are connected to 3, 3, and 1 faces.
splitMesh SPLITMESH Return the connected components of a mesh.
subdivideMesh SUBDIVIDEMESH Subdivides each face of the mesh.
SOURCE CODE
function edges = meshEdges(faces, varargin)
%MESHEDGES Computes array of edge vertex indices from face array.
%
%   EDGES = meshEdges(FACES);
%
%   Example
%     meshEdges
%
%   See also
%     meshes3d, meshEdgeFaces, meshFaceEdges
% ------
% Author: David Legland
% e-mail: david.legland@grignon.inra.fr
% Created: 2011-06-28,    using Matlab 7.9.0.529 (R2009b)
% Copyright 2011 INRA - Cepia Software Platform.
%   HISTORY
%   2013-08-22 rename from computeMeshEdges to meshEdges, add more control
%       on inputs
%% Process input arguments
if isstruct(faces) && isfield(faces, 'faces')
    % if input is a mesh structure, extract the 'faces' field
    faces = faces.faces;
elseif nargin > 1
    % if two arguments are given, keep the second one
    faces = varargin{1};
end
if ~iscell(faces)
    %% Process faces given as numeric array
    % all faces have same number of vertices, stored in nVF variable
    % compute total number of edges
    nFaces  = size(faces, 1);
    nVF     = size(faces, 2);
    nEdges  = nFaces * nVF;
    % create all edges (with double ones)
    edges = zeros(nEdges, 2);
    for i = 1:nFaces
        f = faces(i, :);
        edges(((i-1)*nVF+1):i*nVF, :) = [f' f([2:end 1])'];
    end
else
    %% faces are given as a cell array
    % faces may have different number of vertices
    % number of faces
    nFaces  = length(faces);
    % compute the number of edges
    nEdges = 0;
    for i = nFaces
        nEdges = nEdges + length(faces{i});
    end
    % allocate memory
    edges = zeros(nEdges, 2);
    ind = 0;
    % fillup edge array
    for i = 1:nFaces
        % get vertex indices, ensuring horizontal array
        f = faces{i}(:)';
        nVF = length(f);
        edges(ind+1:ind+nVF, :) = [f' f([2:end 1])'];
        ind = ind + nVF;
    end
end
% keep only unique edges, and return sorted result
edges = sortrows(unique(sort(edges, 2), 'rows'));