Description of writeMesh
Home > matGeom > meshes3d > writeMesh.m
writeMesh
PURPOSE
Write 3D mesh data by inferring format from file name.
SYNOPSIS
function writeMesh(fileName, vertices, faces, varargin)
DESCRIPTION
 Write 3D mesh data by inferring format from file name.
   writeMesh(FNAME, V, F)
   writeMesh(FNAME, MESH)
   Example
   writeMesh
   See also
     meshes3d, readMesh, writeMesh_off, writeMesh_ply, writeMesh_stl
CROSS-REFERENCE INFORMATION
This function calls:
writeMesh_off WRITEMESH_OFF Write a mesh into a text file in OFF format.
writeMesh_ply WRITEMESH_PLY Write a mesh into a file in PLY format.
writeMesh_stl WRITEMESH_STL Write mesh data in the STL format.
This function is called by:
SOURCE CODE
function writeMesh(fileName, vertices, faces, varargin)
% Write 3D mesh data by inferring format from file name.
%
%   writeMesh(FNAME, V, F)
%
%   writeMesh(FNAME, MESH)
%
%   Example
%   writeMesh
%
%   See also
%     meshes3d, readMesh, writeMesh_off, writeMesh_ply, writeMesh_stl
%
% ------
% Author: David Legland
% e-mail: david.legland@inrae.fr
% INRAE - BIA Research Unit - BIBS Platform (Nantes)
% Created: 2020-11-20,    using Matlab 9.8.0.1323502 (R2020a)
% Copyright 2020 INRAE.
% check inputs
if ~ischar(fileName)
    error('First argument must contain the name of the file');
end
% optionnaly parses data
if isstruct(vertices)
    if nargin > 2
        varargin = [{faces} varargin{:}];
    end
    faces = vertices.faces;
    vertices = vertices.vertices;
end
[~, ~, ext] = fileparts(fileName);
switch lower(ext)
    case '.off'
        writeMesh_off(fileName, vertices, faces);
    case '.ply'
        writeMesh_ply(fileName, vertices, faces, varargin{:});
    case '.stl'
        writeMesh_stl(fileName, vertices, faces, varargin{:});
    otherwise
        error('Unrecognized file format for rezading mesh: %s', ext);
end