Description of distancePointPolygon
Home > matGeom > polygons2d > distancePointPolygon.m
distancePointPolygon
PURPOSE
DISTANCEPOINTPOLYGON Shortest distance between a point and a polygon.
SYNOPSIS
function minDist = distancePointPolygon(point, poly)
DESCRIPTION
DISTANCEPOINTPOLYGON Shortest distance between a point and a polygon.
   DIST = distancePointPolygon(POINT, POLYGON)
   Computes the shortest distance between the point POINT and the polygon
   given by POLYGON. POINT is a 1-by-2 row vector, and POLYGON is a N-by-2
   array containing vertex coordinates.
   The distance is computed as the minimal distance to the boundary edges.
   Example
     % Computes the distance between a point and a square
     square = [0 0; 10 0;10 10;0 10];
     p0 = [16 3];
     distancePointPolygon(p0, square)
     ans =
          6
   See also
   polygons2d, points2d, distancePointPolyline, distancePointEdge,
   projPointOnPolyline
CROSS-REFERENCE INFORMATION
This function calls:
distancePointPolyline DISTANCEPOINTPOLYLINE Compute shortest distance between a point and a polyline.
This function is called by:
distancePolygons DISTANCEPOLYGONS Compute the shortest distance between 2 polygons.
distancePolygonsNoCross DISTANCEPOLYGONSNOCROSS Compute the shortest distance between 2 polygons.
polygonSymmetryAxis POLYGONSYMMETRYAXIS Try to identify symmetry axis of polygon.
SOURCE CODE
function minDist = distancePointPolygon(point, poly)
%DISTANCEPOINTPOLYGON Shortest distance between a point and a polygon.
%
%   DIST = distancePointPolygon(POINT, POLYGON)
%   Computes the shortest distance between the point POINT and the polygon
%   given by POLYGON. POINT is a 1-by-2 row vector, and POLYGON is a N-by-2
%   array containing vertex coordinates.
%   The distance is computed as the minimal distance to the boundary edges.
%
%   Example
%     % Computes the distance between a point and a square
%     square = [0 0; 10 0;10 10;0 10];
%     p0 = [16 3];
%     distancePointPolygon(p0, square)
%     ans =
%          6
%
%   See also
%   polygons2d, points2d, distancePointPolyline, distancePointEdge,
%   projPointOnPolyline
%
% ------
% Author: David Legland
% e-mail: david.legland@nantes.inra.fr
% Created: 2009-04-30,    using Matlab 7.7.0.471 (R2008b)
% Copyright 2009 INRA - Cepia Software Platform.
% eventually copy first point at the end to ensure closed polygon
if sum(poly(end, :) == poly(1,:)) ~= 2
    poly = [poly; poly(1,:)];
end
% call to distancePointPolyline
minDist = distancePointPolyline(point, poly);