Description of polygonContains
Home > matGeom > polygons2d > polygonContains.m
polygonContains
PURPOSE
POLYGONCONTAINS Test if a point is contained in a multiply connected polygon.
SYNOPSIS
function varargout = polygonContains(poly, point)
DESCRIPTION
POLYGONCONTAINS Test if a point is contained in a multiply connected polygon.
   B = polygonContains(POLYGON, POINT);
   Returns TRUE if the (possibly multi-connected) polygon POLYGON contains
   the point(s) given by POINT.
   This is an extension of the Matlab function inpolygon for the case of
   polygons with holes.
   Example
   POLY = [0 0; 10 0;10 10;0 10;NaN NaN;3 3;3 7;7 7;7 3];
   PT = [5 1;5 4];
   polygonContains(POLY, PT);
   ans =
        1
        0
   See also
   polygons2d, inpolygon, isPointInPolygon
CROSS-REFERENCE INFORMATION
This function calls:
polygonArea POLYGONAREA Compute the signed area of a polygon.
splitPolygons SPLITPOLYGONS Convert a NaN separated polygon list to a cell array of polygons.
This function is called by:
centroidalVoronoi2d CENTROIDALVORONOI2D Centroidal Voronoi tesselation within a polygon.
centroidalVoronoi2d_MC CENTROIDALVORONOI2D_MC Centroidal Voronoi tesselation by Monte-Carlo.
randomPointInPolygon RANDOMPOINTINPOLYGON Generate random point(s) in a polygon.
SOURCE CODE
function varargout = polygonContains(poly, point)
%POLYGONCONTAINS Test if a point is contained in a multiply connected polygon.
%
%   B = polygonContains(POLYGON, POINT);
%   Returns TRUE if the (possibly multi-connected) polygon POLYGON contains
%   the point(s) given by POINT.
%   This is an extension of the Matlab function inpolygon for the case of
%   polygons with holes.
%
%   Example
%   POLY = [0 0; 10 0;10 10;0 10;NaN NaN;3 3;3 7;7 7;7 3];
%   PT = [5 1;5 4];
%   polygonContains(POLY, PT);
%   ans =
%        1
%        0
%
%   See also
%   polygons2d, inpolygon, isPointInPolygon
% ------
% Author: David Legland
% E-mail: david.legland@inrae.fr
% Created: 2007-10-11, using Matlab 7.4.0.287 (R2007a)
% Copyright 2007-2024 INRA - BIA PV Nantes - MIAJ Jouy-en-Josas
% transform as a cell array of simple polygons
polygons = splitPolygons(poly);
N = length(polygons);
Np = size(point, 1);
% compute orientation of polygon, and format to have Np*N matrix
areas = zeros(N, 1);
for i = 1:N
    areas(i) = polygonArea(polygons{i});
end
ccw = areas > 0;
ccw = repmat(ccw', Np, 1);
% test if point inside each polygon
in = false(size(point, 1), N);
for i = 1:N
    poly = polygons{i};
    in(:, i) = inpolygon(point(:,1), point(:,2), poly(:,1), poly(:,2));
end
% count polygons containing point, weighted by polygon orientation
res = sum(in.*(ccw==1) - in.*(ccw==0), 2);
varargout{1} = res;