Description of polygonCentroid
Home > matGeom > polygons2d > polygonCentroid.m
polygonCentroid
PURPOSE
POLYGONCENTROID Computes the centroid (center of mass) of a polygon.
SYNOPSIS
function [centroid, area, Sx, Sy] = polygonCentroid(varargin)
DESCRIPTION
POLYGONCENTROID Computes the centroid (center of mass) of a polygon.
   CENTROID = polygonCentroid(POLY)
   CENTROID = polygonCentroid(PTX, PTY)
   Computes center of mass of a polygon defined by POLY. POLY is a N-by-2
   array of double containing coordinates of vertices.
   [CENTROID, AREA] = polygonCentroid(POLY)
   Also returns the (signed) area of the polygon.
   Example
     % Draws the centroid of a paper hen
     x = [0 10 20  0 -10 -20 -10 -10  0];
     y = [0  0 10 10  20  10  10  0 -10];
     poly = [x' y'];
     centro = polygonCentroid(poly);
     drawPolygon(poly);
     hold on; axis equal;
     drawPoint(centro, 'bo');
   References
     Algorithm adapted from P. Bourke's web page.
   See also
     polygons2d, polygonArea, polygonSecondAreaMoments, drawPolygon
     polylineCentroid, centroid
CROSS-REFERENCE INFORMATION
This function calls:
centroid CENTROID Compute centroid (center of mass) of a set of points.
parsePolygon PARSEPOLYGON Conversion between different polygon formats.
This function is called by:
polygonCentroid3d POLYGONCENTROID3D Centroid (or center of mass) of a polygon.
boundedCentroidalVoronoi2d BOUNDEDCENTROIDALVORONOI2D Create a 2D Centroidal Voronoi Tesselation in a box.
centroidalVoronoi2d CENTROIDALVORONOI2D Centroidal Voronoi tesselation within a polygon.
meshFaceCentroids MESHFACECENTROIDS Compute centroids of faces in a mesh.
clipPolygonByLine CLIPPOLYGONBYLINE Clip a polygon by a directed line.
polygonEquivalentEllipse POLYGONEQUIVALENTELLIPSE Compute equivalent ellipse with same second order moments as polygon.
polygonSymmetryAxis POLYGONSYMMETRYAXIS Try to identify symmetry axis of polygon.
SOURCE CODE
function [centroid, area, Sx, Sy] = polygonCentroid(varargin)
%POLYGONCENTROID Computes the centroid (center of mass) of a polygon.
%
%   CENTROID = polygonCentroid(POLY)
%   CENTROID = polygonCentroid(PTX, PTY)
%   Computes center of mass of a polygon defined by POLY. POLY is a N-by-2
%   array of double containing coordinates of vertices.
%
%   [CENTROID, AREA] = polygonCentroid(POLY)
%   Also returns the (signed) area of the polygon.
%
%   Example
%     % Draws the centroid of a paper hen
%     x = [0 10 20  0 -10 -20 -10 -10  0];
%     y = [0  0 10 10  20  10  10  0 -10];
%     poly = [x' y'];
%     centro = polygonCentroid(poly);
%     drawPolygon(poly);
%     hold on; axis equal;
%     drawPoint(centro, 'bo');
%
%   References
%     Algorithm adapted from P. Bourke's web page.
%
%   See also
%     polygons2d, polygonArea, polygonSecondAreaMoments, drawPolygon
%     polylineCentroid, centroid
% ------
% Author: David Legland
% E-mail: david.legland@inrae.fr
% Created: 2004-05-05
% Copyright 2004-2024
% parse input arguments
if nargin == 1
    poly = varargin{1};
elseif nargin == 2
    poly(:,1) = varargin{1};
    poly(:,2) = varargin{2};
end
poly = parsePolygon(poly, 'repetition');
px = poly(:,1);
py = poly(:,2);
% vertex indices
N = length(px);
iNext = [2:N 1];
% compute cross products
common = px .* py(iNext) - px(iNext) .* py;
Sx = 1/6*sum((py + py(iNext)) .* common);
Sy = 1/6*sum((px + px(iNext)) .* common);
% area and centroid
area = sum(common) / 2;
centroid = [Sy Sx] / area;