Description of edgeToLine
Home > matGeom > geom2d > edgeToLine.m
edgeToLine
PURPOSE
EDGETOLINE Convert an edge to a straight line.
SYNOPSIS
function line = edgeToLine(edge)
DESCRIPTION
EDGETOLINE Convert an edge to a straight line.
   LINE = edgeToLine(EDGE);
   Returns the straight line containing the edge EDGE.
   EDGE is represented as [X1 Y1  X2 Y2]
   LINE is represented as [X0 Y0  DX DY]
   Example
       edge = [2 3 4 5];
       line = edgeToLine(edge);
       figure(1); hold on; axis([0 10 0 10]);
       drawLine(line, 'color', 'g')
       drawEdge(edge, 'linewidth', 2)
   See also
   edges2d, lines2d, lineToEdge
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
parallelEdge PARALLELEDGE Edge parallel to another edge.
intersectEdgePolygon INTERSECTEDGEPOLYGON Intersection point of an edge with a polygon.
intersectLinePolyline INTERSECTLINEPOLYLINE Intersection points between a line and a polyline.
SOURCE CODE
function line = edgeToLine(edge)
%EDGETOLINE Convert an edge to a straight line.
%
%   LINE = edgeToLine(EDGE);
%   Returns the straight line containing the edge EDGE.
%   EDGE is represented as [X1 Y1  X2 Y2]
%   LINE is represented as [X0 Y0  DX DY]
%
%   Example
%       edge = [2 3 4 5];
%       line = edgeToLine(edge);
%       figure(1); hold on; axis([0 10 0 10]);
%       drawLine(line, 'color', 'g')
%       drawEdge(edge, 'linewidth', 2)
%
%   See also
%   edges2d, lines2d, lineToEdge
%
% ------
% Author: David Legland
% e-mail: david.legland@inra.fr
% Created: 2009-07-23,    using Matlab 7.7.0.471 (R2008b)
% Copyright 2009 INRA - Cepia Software Platform.
line = [edge(:, 1:2) edge(:, 3:4)-edge(:, 1:2)];