Description of lineAngle
Home > matGeom > geom2d > lineAngle.m
lineAngle
PURPOSE
LINEANGLE Computes angle between two straight lines.
SYNOPSIS
function theta = lineAngle(varargin)
DESCRIPTION
LINEANGLE Computes angle between two straight lines.
   A = lineAngle(LINE);
   Returns the angle between horizontal, right-axis and the given line.
   Angle is given in radians, between 0 and 2*pi, in counter-clockwise
   direction.
   A = lineAngle(LINE1, LINE2);
   Returns the directed angle between the two lines. Angle is given in
   radians between 0 and 2*pi, in counter-clockwise direction.
   See also
   lines2d, angles2d, createLine, normalizeAngle
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 31/10/2003.
CROSS-REFERENCE INFORMATION
This function calls:
lineAngle LINEANGLE Computes angle between two straight lines.
This function is called by:
angle3Points ANGLE3POINTS Compute oriented angle made by 3 points.
angleSort ANGLESORT Sort points in the plane according to their angle to origin.
bisector BISECTOR Return the bisector of two lines, or 3 points.
edgeAngle EDGEANGLE Return angle of edge.
lineAngle LINEANGLE Computes angle between two straight lines.
pointOnLine POINTONLINE Create a point on a line at a given position on the line.
radicalAxis RADICALAXIS Compute the radical axis (or radical line) of 2 circles.
revolutionSurface REVOLUTIONSURFACE Create a surface of revolution from a planar curve.
geod2cart GEOD2CART Convert geodesic coordinates to cartesian coord.
SOURCE CODE
function theta = lineAngle(varargin)
%LINEANGLE Computes angle between two straight lines.
%
%   A = lineAngle(LINE);
%   Returns the angle between horizontal, right-axis and the given line.
%   Angle is given in radians, between 0 and 2*pi, in counter-clockwise
%   direction.
%
%   A = lineAngle(LINE1, LINE2);
%   Returns the directed angle between the two lines. Angle is given in
%   radians between 0 and 2*pi, in counter-clockwise direction.
%
%   See also
%   lines2d, angles2d, createLine, normalizeAngle
%
%   ---------
%   author : David Legland
%   INRA - TPV URPOI - BIA IMASTE
%   created the 31/10/2003.
%
%   HISTORY
%   2004-02-19 added support for multiple lines.
%   2011-01-20 use bsxfun
nargs = length(varargin);
if nargs == 1
    % angle of one line with horizontal
    line = varargin{1};
    theta = mod(atan2(line(:,4), line(:,3)) + 2*pi, 2*pi);
elseif nargs==2
    % angle between two lines
    theta1 = lineAngle(varargin{1});
    theta2 = lineAngle(varargin{2});
    theta = mod(bsxfun(@minus, theta2, theta1)+2*pi, 2*pi);
end